dubbo:
  scan:
    base-packages: com.example.webdubbo
  protocols:
    dubbo:
      name: dubbo
      port: -1
  consumer:
    timeout: 5000
    check: false
    retries: 0
  cloud:
    subscribed-services:
