spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
  # 访问链接http://127.0.0.1:9900/api-web/test/abc
      routes:
        - id: web
          uri: lb://web-dubbo
          predicates:
            - Path=/api-web/**
          filters:
            - StripPrefix=1
